language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
install:
  - "pip install -r requirements-tests.txt"
  - "python setup.py install"
script: nosetests --with-coverage --cover-package within -v
after_success:
  - coveralls
